/*
 * 你的留言牆｜可自行編輯的匿名留言庫
 *
 * 這個檔案會優先被 note-wall.html 讀取。只改雙引號內的文字，請保留其餘括號、逗號、冒號與結構。
 * BANK：每張匿名紙條的主句。RESPONSE_TAILS：可能加在主句後面的收尾；空字串 "" 代表不加收尾。
 * BLOCKED_PHRASES：已標註為不想再出現的句型；即使仍寫在 BANK 裡，留言牆也不會抽取它。
 */

window.YOUR_NOTE_WALL_LIBRARY = {
  "version": 2,
  "BANK": {
    "zh": {
      "fatigue": [
        "這段路如果走得很慢，也沒有關係。",
        "願你不用一直向誰證明什麼。",
        "路過留一張：希望你回去的路上，有一小段路是安靜的。",
        "今天先把力氣用在自己身上也可以。",
        "陌生人，有些事情晚一點再想也沒關係的！Let it go~",
        "這張紙沒有催你的意思，這只是一張紙。 ——by紙。",
        "如果今天只做到這裡，好像也夠了，下！班！",
        "希望你的肩膀今晚可以鬆一點。",
        "陌生人，有些事情晚一點再想也沒關係。",
        "這張紙沒有催你的意思，這只是一張紙。",
        "今天的清單可以有空格，那是正常的呼吸。",
        "偶爾臉可以放空，笑容不是每一刻的義務。",
        "小聲提醒，累不等於沒用。",
        "複雜的問題可以先放進抽屜，晚點再打開看。",
        "隔壁的貓也有懶著的日子，你也可以。",
        "你今天已經比昨天的自己前進了一點，哪怕很小。",
        "沒馬上回訊息，可能只是暫時選擇安靜。",
        "把今天的雜音想像成背景的電風扇，存在但可以忽略。",
        "有些努力看不到，但會像暗槓一樣慢慢變多。",
        "當腦袋熱得像湯，蓋上蓋子等待冷卻也合理。",
        "今天不必為明天排太多劇情，先讓場景停止一下。",
        "散亂的房間也會講故事，不用每次都當掃得乾淨。",
        "把對某件事的熱情當成一件厚外套，想脫就脫。",
        "外表正常的人，也許暗藏省電模式。",
        "拖延有時像系統更新，慢一點不一定壞事。",
        "世界不只要你跑，偶爾躺著它也會繼續轉。",
        "今天的難關說不定會成為明天的笑料。",
        "讓窗外的光慢慢變少，別急著追上每個日程。",
        "失敗感像穿睡衣出門，尷尬但不會致命。",
        "工作像地心引力，放手一下也會輕微飄浮。"
      ],
      "lonely": [
        "有些話說不出口也沒關係。留在這裡，就已經有人看見了。",
        "這張紙沒有什麼答案，只是想留在這裡。",
        "剛好路過，剛好看見，想你知道這兒有人關心你。",
        "希望今天有一個瞬間，讓你覺得自己不是透明的。",
        "我不知道你的生活，但這張紙背後的人，希望人和人之間多點温暖。",
        "有些人不是不在，只是不知道怎麼靠近，希望有善意抵達你的心。",
        "把這句放在牆上，好像就沒有那麼空蕩了。",
        "我不知道你的生活，但這張紙背後的人，希望人和人之間多點溫暖。",
        "不是每個人都不在，有的人只是還不知道怎麼靠近，希望有善意抵達你的心。",
        "貼在牆上的這句話，好像就沒有那麼空蕩了。",
        "窗外下雨了，我想把這張紙塞進你口袋裡，當作一個不刺眼的問候。",
        "有時我只是想讓字留在別人的視線裡，證明我們曾同一個房間呼吸過。",
        "如果牆會回話，希望它說：我看見了你今天的模樣。",
        "一句無關緊要的話貼在這裡，像是人群裡的小旗子。",
        "路燈下的影子也會寂寞，別以為只是你一個人。",
        "我把遺忘的笑聲折成小紙條，放在這兒給路過的人。",
        "有人把故事悄悄放在這裡，沒標題也不完整，但足夠讓人想起自己。",
        "你不需要立刻回答這張紙，它會乖乖待在牆上等你。",
        "哪怕只是短短一句，能被看見就值得我寫下來。",
        "心情有時候像冷氣，沒預警就吹來，這張紙是件薄外套。",
        "有些日子像沒聲音的電視，貼張紙在牆上，討回一點聲音。",
        "誰說牆只能掛畫？有時候它也需要尷尬的小紙條。",
        "我不知道怎麼敘述平凡，就把一個平凡的留言留在這裡。",
        "看到這張紙的人，如果正好需要一個陌生的眼神，這裡有一個。",
        "寫下名字會太沉重，寫下一句話剛好，輕一點。",
        "想像有人在對面的咖啡店看見這句話，然後笑了一下。",
        "在這個牆的小角落，放一點不被安排的存在感。",
        "不確定的心事折成摺痕，貼在牆上，它們比較不會跑掉。",
        "城市太大，聲音太多，這張小紙是給安靜的聽眾。",
        "我不是來解釋的，只是帶來一點溫柔，放在你可以忽略的地方。"
      ],
      "uncertain": [
        "不用現在就替這件事取一個結論。",
        "希望你手上那件放不下的事，會有一點一點鬆開的時候。",
        "答案晚一點來，也不是壞事。",
        "今天不知道，也可以。",
        "有些岔路走過才知道長什麼樣子。",
        "留一顆畫得不太圓的星星給你。",
        "這張memo是個提示，follow your heart。",
        "也許答案躲在一杯未喝完的咖啡裡。",
        "先把這件事放一邊，別讓它佔滿整個腦袋。",
        "別急著把選擇當成永遠的決定。",
        "或許等你回頭看，現在會像個有趣的插曲。",
        "偶爾保持一點疑問，比裝懂來得誠實。",
        "如果方向看不清，試試把問題講給別人聽。",
        "讓選項自己慢慢排隊，你再看看哪個笑得真。",
        "當下的猶豫不是失敗，只是訊號之一。",
        "把這個問號畫得大一點，可能比較好發現下一步。",
        "小聲地承認不知道，會讓人比較真實。",
        "換種角度看，有時候疑惑會變成風景。",
        "早一點確定不代表早一點安心。",
        "未必現在要做選擇，時間也會幫你排序。",
        "越急著收線，越容易扯斷那根本就還沒做好的線。",
        "試著把心事放成草稿，你可以改很多次。",
        "想像答案像一張還未完成的海報，顏色還在乾。",
        "暫時不去定義，也是一種溫柔的保留。",
        "多留一點空間給突發的念頭或突來的笑。",
        "再等等看，事情有時候會自己把邏輯排好。",
        "嘗試用笨方法試一次，看看會不會出現新的路。",
        "若是你現在覺得亂，代表你還活著在選擇。",
        "看著那份清單，你可能會發現有幾項其實不用挑。",
        "安靜地坐一下，讓腦中的選項互相說完話。"
      ],
      "frustration": [
        "嗯……聽說把紙張撕掉可以解壓，實在受不住，要不試試？",
        "有些日子就是很不適合假裝沒事。",
        "我今天畫圖畫的時侯也畫得很亂，讓我很不開心 :(",
        "如果很煩，這張Memo可以先幫你承受一下。",
        "不用把委屈立刻吞下。",
        "事情不順利的時候，連空氣都會比較燥熱。",
        "這裡可以留下那些不好聽的話，然後，Let it go。",
        "我今天畫圖畫的時候也畫得很亂，讓我很不開心。",
        "我很想大喊，但講出來又覺得怪尷尬，就先寫在這邊。",
        "剛剛又被小事絆到了，心情像被膠帶黏住一樣。",
        "別問我為什麼沉默，我連自己都在生氣。",
        "今天的我連咖啡都不想欣賞，只想把桌子踢一腳。",
        "每次排隊到半夜，世界都變得特別小，煩躁就跑出來了。",
        "有人把我的努力當空氣，真的會很想把那空氣堵住。",
        "心裡有一隻小蟲一直在吱吱叫，怎麼也停不下來。",
        "想把那些令人不舒服的訊息剪掉，但手機在手，剪不掉。",
        "時間像慢動作播放，我的情緒卻像被快轉，完全不同步。",
        "別告訴我淡定，現在的我連假裝都很累。",
        "明明準備好了還被打斷，所有的氣都不見了。",
        "跟別人說話像丟石頭，回音都變成挑剔的話。",
        "我把不爽寫下來，然後發現紙比人還誠實。",
        "把鑰匙掉在沙發縫，然後找半小時，那種想罵街的感覺。",
        "等公車等到腦袋空轉，心裡的火苗越來越起來。",
        "想把桌上的東西全推倒，但又怕清理更累，只好在心裡推。",
        "被別人誤解比被誤會還更煩，講了也像把空氣對著牆壁說話。",
        "有些話想說出口，話到嘴邊又被禮貌吞回去。",
        "好想把今天的對話做個剪輯，刪掉那些尷尬片段。",
        "心裡的小劇場在重播，場景都是同一個尷尬畫面。",
        "每次提醒別人，反而變成自己在反覆受傷。",
        "想把抓狂的聲音收藏起來，留到沒人的時候播放。"
      ],
      "gratitude": [
        "收到了，謝謝你，陌生人。",
        "那就很好。今天我這邊也有一點點好事發生了，也值得記下來。",
        "這兒收到了特地發來感謝。",
        "你的謝謝看起來有點暖。",
        "路過的人也收到了一小塊心意。",
        "這張紙想替這個瞬間佔個位置。",
        "兜兜轉轉，好事終於如期而至。",
        "剛好有人幫我撿起掉在地上的飲料，真的很感謝。",
        "早餐店的阿姨今天多放了一匙糖，心情有點輕。",
        "被公車司機等了一下，趕上了班，謝謝那份耐心。",
        "那句簡短的「辛苦了」，意外地讓我暖了一下。",
        "收到一杯暖咖啡的味道，像有人在遠處招呼我。",
        "借我筆的那個瞬間，悄悄幫我渡過尷尬，謝謝。",
        "曬衣夾不見了，鄰居還給我，瞬間放心了。",
        "今晚有人回了我的訊息，比我預期的早，覺得被看見。",
        "小店老闆多找了零頭，覺得被寵了一下。",
        "圖書館幫我留了那本書，剛好要用，謝謝。",
        "一個陌生人的微笑在下雨天派上用場，暖了一路。",
        "朋友替我攪拌的那碗泡麵，讓我晚餐有個小確幸。",
        "被提醒帶傘的人，今天沒有被雨淋成落湯雞，謝謝。",
        "有人幫忙按電梯，送我到樓下，省了等的時間。",
        "包裹裡多塞了一張小紙條，內容雖短但暖心。",
        "那張送錯的票被還回來了，省了一場麻煩，謝謝。",
        "今晚有人借我外套，雖然簡單但很溫暖。",
        "被咖啡店記住了我的名字，覺得被記得，很意外的喜歡。",
        "有人幫我把腳踏車推上坡，少了好多喘氣的瞬間。",
        "郵差在雨中把包裹放好，感謝這種默默的用心。",
        "夜市大排檔的阿姨多給了一份配菜，今晚多了點開心。",
        "路燈下那段短促的聊天，讓我不那麼孤單。",
        "我把這塊小心意留在牆上，謝謝你來看它。"
      ],
      "share": [
        "omggg 這件事很好！先貼在這兒，不要讓今天後來那些亂七八糟的事把它蓋掉！",
        "我想像了一下。這種小事被你捕捉到，也是件美好的事。",
        "原來你等這一天等了好一陣子。那就先不要急著假裝沒什麼事發生，這個需要慶祝！",
        "oh！今天留言牆上多了一個美好瞬間。",
        "真好！我也想把這件事記下來，所以我已經拿出了並且收回我的手機。",
        "真好，替你高興。",
        "你不知道我是誰，但我剛好看到，哈！",
        "只是路過，不小心看到了這兒。留個紀念。",
        "這個memo 要留久一點，好人好事晚點再看也會覺得開心。",
        "剛剛路過，看到你貼的，就覺得世界小小地亮了一下。",
        "這個瞬間有點安靜，像是城市裡的秘密花園。",
        "我也曾有過類似感覺，看到你寫的心情像被回聲補了一句。",
        "這瞬間值得被按住一下，等會兒再笑起來也不奇怪。",
        "小確幸報到，專屬的牆角已經被認領了。",
        "這個細節很容易被忽略，幸好你抓到它。",
        "照片沒拍好也沒關係，這邊的文字就夠溫柔了。",
        "我猜你也有點尷尬地笑，這樣剛好。",
        "這裡像是小型時間膠囊，大家偷偷放進快樂。",
        "笑一小下也可以，之後再決定要不要告訴別人。",
        "謝謝你把這件小事帶到公共空間，讓別人也能偷看。",
        "這種被看見的感覺真奇妙，像有人在街角對你眨眼。",
        "這張便條很會讓人想起某個味道或聲音。",
        "看到這句話心裡暖了一下，然後又想笑。",
        "有種想把這件事摺起來放口袋的衝動。",
        "有的人會快速滑過，有的人會停留，今天你抓到了停留的人。",
        "這裡的每一張紙都像是小小的秘密交換站。",
        "也許等個幾年再回來看，會覺得當時的自己很可愛。",
        "這條留言證明了生活裡還有讓人傻笑的地方。",
        "我不常寫東西，但看到這句，還是想留下來。",
        "明明是別人的故事，卻讓我心裡長出一個小插曲。"
      ],
      "blessing": [
        "也希望這句有回到你身上。",
        "這句祝福在牆上繞一圈。",
        "有人收到你留的好意了。",
        "我就不客氣沾點祝褔了。",
        "願你今天也有一口熱的。",
        "這張memo想替你把祝福放大一點點……！",
        "窗外的風聲幫你把祝福帶來了。",
        "某個角落有人偷偷為你笑了。",
        "把好運悄悄塞進你不常注意的口袋裡。",
        "希望你遇到的是溫柔又不太費事的那種。",
        "不管今天有沒有驚喜，至少有這張小紙片在。",
        "小確幸藏在你常經過的地方，偶爾會被發現。",
        "下午如果多出一點空檔，我會替你暗暗開心。",
        "今天的雜事先後讓位給一點小安穩就好。",
        "希望你喝到的每杯飲料都剛剛好，不太甜也不太貴。",
        "遇到的人若都帶來一點好心情，那就恰到好處。",
        "這是一張隨手送出的幸運票，無法退換也無法退貨。",
        "要是房間有點亂，祝福會自動導航過去。",
        "等電梯的那幾分鐘，說不定你會突然笑出來。",
        "收到的訊息多半是好消息，偶爾還會附上段子。",
        "一點運氣放在口袋，偷偷分享一半也不錯。",
        "今天的小麻煩短暫又帶點可愛就足夠了。",
        "這張紙負責把平凡瞬間變成小確幸。",
        "這句像口袋裡的糖，必要時偷偷吃一顆。",
        "祝你不被突如其來的鳥屎黏住，躲得漂亮。",
        "今天天氣若好，願你正好被太陽撞到。",
        "好事不一定敲門，它更會在縫隙塞張便條。",
        "祝福比咖啡便宜，也更容易上癮。",
        "給你的不是完整劇本，只是幾個小驚喜和運氣。",
        "牆上這張小紙提醒世界：有人值得被好待。"
      ],
      "affirmation": [
        "這句看起來很適合貼久一點。",
        "借我看一眼。嗯，這句不錯。",
        "有些話不急著有用，喜歡就先留著。",
        "這張不要撕掉……plsssss",
        "它看起來像是會陪很久的一句話。",
        "我想在旁邊畫一隻慢慢走的小蝸牛。",
        "陌生人考慮出書嗎，你當時要退出文壇的時候我是拒絕的。",
        "今天翻到這張就笑了兩秒，夠了。",
        "如果你今天沒辦法把所有東西排好，也沒關係。",
        "暫時藏起來也可以，等你想起來再看。",
        "我喜歡你忘記手機在沙發上的時候慌張的樣子。",
        "這句話像是昨天買的熱可可，暖但不燙。",
        "先把眼前這小事放進口袋，明天再掏出來。",
        "有些答案會在走路的時候冒出來，今天就先走一走吧。",
        "你不必把每件事情都變成故事的高潮。",
        "小聲說，這世界比你想得還多笑點。",
        "這裡可以放你不想讓別人看到的那張笑臉照片。",
        "我幫你把昨天的混亂收了一點，還給你一半空白。",
        "今晚別把所有好想法都藏起來，留一條線給明天。",
        "有時候遺忘是給自己一場小小的假。",
        "你會笑到覺得這不過癮的那一天，現在先收藏這句話。",
        "這句話像那種沒人注意的小幸運，先悄悄收好。",
        "今天做不到也沒關係，明天一樣有空氣。",
        "偶爾走錯路也是為了發現不一樣的風景。",
        "有些事情值得慢慢看，就像把手上的線慢慢鬆開。",
        "如果需要理由重新開始，這張就當那個小理由吧。",
        "這裡保留一個位置給突如其來的好點子。",
        "不用每次都把自己說明得清清楚楚，模糊也很好。",
        "曾經覺得荒唐的想法，有時候會變成晚餐的笑料。",
        "毫無鋪陳地喜歡一件小事，也是一種勇敢。"
      ],
      "complex": [
        "看完覺得像不是一件事壓著你，是很多件事剛好一起擠進來。這樣當然會很難呼吸。",
        "這麼長一段不是你太多事，是事情真的太多。",
        "不用擔心，先不用把它們排成一個很漂亮的故事。亂一點也沒關係。",
        "我不知道全部，但看起來這陣子真的過得不順……",
        "有些日子像房間裡同時開了幾台風扇，怎樣都靜不下來。",
        "這張紙先放一把大一點的傘給你。",
        "如果你現在只想把事情倒出來，也可以，不用急。",
        "感覺像不是一件事壓著你，是很多件事剛好一起擠進來。這樣當然會很難呼吸。",
        "別覺得每件小事都要立刻解決，先把它們攤平在桌上看看就好。",
        "有時候混亂本身就是訊號，不是你的失敗證明。",
        "提醒炸了就像腦袋裡的便利貼，暫時都很喧鬧。",
        "你可以對自己說一句很短的真話，不用修飾也不要對外解釋。",
        "說出來的順序可以亂，重要的是把那些東西從肚子裡搬出來。",
        "有些人看起來都很鎮定，但裡面可能也在整理亂七八糟的線頭。",
        "振動時刻常常比真正重要的事還響亮。",
        "把所有想做和該做的寫在一張紙上，不用分類，只是把聲音放出來。",
        "那些小小的缺口其實會讓壓力漏出來一點，不用怕有漏洞。",
        "聽說時間不會立刻修好一切，但它會讓你發現哪些東西還值得繼續牽掛。",
        "人會在累到快不住時變得很誠實，連對自己的期待也說不出話。",
        "連選擇不回應都是一種考慮的方式。",
        "偶爾覺得自己像個多工機器，但其實只是被放滿了太多窗格。",
        "誰都不必一直是最堅硬的那塊磐石，偶爾裂了也能重組成別的形狀。",
        "把時間想像成一片布，有些皺褶不是你的錯。",
        "不需要每一個人都理解你的地圖，能有人在旁邊聽你講就好。",
        "今天的焦躁可能只是明天故事的一個插圖，不是全部章節。",
        "你不必把所有不確定的東西當成秘密，可以先對自己說清楚一點。",
        "有些情緒像沒煮熟的飯，放久了會黏住腳步。",
        "別急著把每件事都放進標籤裡，它們有時候只是暫時的噪音。",
        "當事情像重播的歌詞不停回來，可以試著把曲子暫停一下聽聽背景聲。",
        "別忘了，混亂裡也有小小的日常，比如那杯還熱的茶。"
      ],
      "silence": [
        "今天的字好像都請假了。",
        "那我先貼一張沒有內容的。",
        "嗯。這張紙點了點頭。",
        "只留一個符號也算到過這裡。",
        "窗外的風在輕聲講話，我在記筆記給空氣。",
        "桌上的杯子睡著了，紙還保持清醒。",
        "忘記要寫什麼了，於是改寫忘記本身。",
        "這裡是空白的存放處，留給過路的念頭。",
        "有時候沉默會敲門，然後悄悄坐下來。",
        "我把聲音摺成一隻小船，放在角落裡。",
        "這張紙像按下了暫停鍵，畫面還有呼吸。",
        "只貼了半句話，另一半給了想像去完成。",
        "原本以為會爆發，結果只是輕輕散了。",
        "這裡藏了一個問題：怎麼形容沒有字。",
        "眼睛放在空處，會不小心看到回音。",
        "旁邊那張比我還擅長沉默，讓我有點小羨慕。",
        "字似乎跟日曆做了約定，今天輪到會議空檔。",
        "如果沉默有顏色，應該是淡薄的灰藍。",
        "我想偷走一點安靜，結果只拿到一角紙。",
        "筆頭也會偷懶，於是留下這張無業通知。",
        "我畫了個圈，圈住了暫時不說的那些句子。",
        "這張紙守口如瓶，什麼都沒透露。",
        "空白讓人想像，現在先暫停想像的排隊。",
        "我跟紙比賽誰更安靜，最後兩者都輸給時間。",
        "一個小符號像訪客，敲完門就悄悄走了。",
        "好像有人在耳邊說話，結果只是空氣翻頁。",
        "我給沉默貼了標籤，寫著「暫時停留」。",
        "這裡只給短暫停靠的念頭，請減少行李。",
        "有時什麼都不寫，反而給別的聲音坐坐。",
        "把空白貼上牆，好像把時間暫藏在抽屜裡。"
      ],
      "neutral": [
        "路過，放一張。",
        "這張紙只是覺得這裡還可以再多一點顏色。",
        "今天牆上有一小塊空白，先放這裡。",
        "沒有特別要說什麼，只是想貼一張。",
        "這面牆好像慢慢變得有點熱鬧。",
        "留給下一個路過的人。",
        "我本來沒有要寫什麼，但還是留個字。",
        "感覺牆慢慢變得有點熱鬧。",
        "剛好有張紙在口袋裡，剛好這裡有空位。",
        "看見牆就想試試不同的顏色搭配，於是貼了。",
        "放一張，讓角落看起來沒那麼寂寞。",
        "如果牆會說話，它可能會喜歡這張小小的訪客。",
        "沒什麼宣言，只是偷偷做了件小事。",
        "當作一個小小記號，給路過的眼睛一點驚喜。",
        "想像這面牆是城市的素描本，這是我的隨手一筆。",
        "不急著解釋，就先貼上了。",
        "或許某個晚上有人會把它當作迷路時的訊號。",
        "為了證明今天我也有來過這個街角。",
        "格子太整齊了，想添個隨性的角落。",
        "假如這張紙被風吹走，那也算是冒險的延伸。",
        "沒有目的地，只是覺得顏色應該散步一下。",
        "牆上本來就有很多故事，這只是其中一頁。",
        "先占個位，等更多故事來填進來。",
        "做了一件小事，其他的留給時間。",
        "想像有一百張貼滿整面牆，覺得有點好笑。",
        "它證明有人曾經看過這面牆。",
        "有時候就是想把一點隨機放在日常裡。",
        "把平凡的牆當成一本可翻的日記。",
        "有點想把心情藏進紙裡，於是動手了。",
        "只是好奇牆上還能藏下多少小東西。"
      ]
    },
    "en": {
      "fatigue": [
        "It is all right if this part of the road is slow.",
        "You do not have to keep proving something all the time.",
        "A note from someone passing by: I hope a small part of your way home is quiet.",
        "You can spend your energy on yourself today.",
        "Some things can wait until later without disappearing.",
        "This note is not rushing you.",
        "If this is all you could do today, maybe it is enough.",
        "Let the to-do list sit. It doesn't measure you.",
        "No one needs a full explanation for why you're tired.",
        "Small steps count, even if they feel invisible.",
        "The house can be messy for a little while. It won't swallow you.",
        "The pace isn't the problem; the road is heavy right now.",
        "Rest isn't a failure; it's a change of speed.",
        "Inbox at zero isn't a measure of worth.",
        "Saying no is allowed even without a neat reason.",
        "Today might be more about holding on than moving forward.",
        "It's fine to leave some lights off for now.",
        "Someone else can handle the tiny tasks today if that helps.",
        "Quiet does work, even when it doesn't look like work.",
        "You're not lazy; your energy has limits.",
        "Tiny wins look ordinary, but they're real.",
        "Save your stubbornness for later. Rest can use it now.",
        "If talking feels hard, a blank text still says I'm here.",
        "A day doesn't need to be full to mean something.",
        "There is no rule that says you must sparkle today.",
        "Softness can carry you through; toughness can wait.",
        "Slow days are a shape of life, not a flaw in you.",
        "Let the calendar have empty boxes for a change.",
        "Pause now so later won't feel like a cliff.",
        "Wear your tired like a coat, not a scar."
      ],
      "lonely": [
        "It is all right if some things do not come out in words. Leaving them here is already something.",
        "This note has no answer. It just wanted to be here.",
        "Passing by. Happened to see this.",
        "I hope there is one moment today when you do not feel invisible.",
        "I do not know all of it, but this note paused for a moment.",
        "Putting this on the wall makes it feel a little less empty.",
        "I watched someone drop a coffee and thought about how small things can wobble a day.",
        "Left here because the room felt too loud for thinking.",
        "If someone needed an excuse to sigh, consider this it.",
        "There was a song stuck in my head and I wanted to leave the chorus somewhere public.",
        "I don't want to fix anything; I just wanted to notice this corner with you.",
        "The street smelled like rain and bread today. It felt worth mentioning.",
        "This scrap of paper is trying to hold a quiet, nothing more.",
        "I folded my day into a square and set it here.",
        "For whoever's hands find this: the moment was real, however small.",
        "I spent ten minutes watching a cloud decide, then left this.",
        "No advice, no plan; only the quiet fact that I saw something.",
        "This is a small witness to a day that moved slowly.",
        "It feels strange to speak to a wall, so I wrote instead.",
        "Someone laughed nearby and it made the world seem less heavy for a second.",
        "I meant to say more, then the bus came.",
        "Left because I liked the color of the light on the sidewalk.",
        "If this meets someone who needs to pause, take it as a gentle pause.",
        "There is a missing line here that I couldn't write.",
        "I carried a blank space all morning and now it's on the wall.",
        "One small admission: I wished for company in the grocery aisle.",
        "I am practicing letting small things exist without explaining them.",
        "This note is a tiny attendance: I was present here for a moment.",
        "Sometimes I notice ordinary evidence that I'm not the only person moving through the day.",
        "If you're also pretending everything is fine, we can pretend together for a minute."
      ],
      "uncertain": [
        "You do not have to give this a final answer tonight.",
        "I hope the thing you cannot put down loosens, little by little.",
        "An answer arriving later is not a bad answer.",
        "It is okay not to know today.",
        "Some turns only make sense after you take them.",
        "Leaving a star that is not quite round.",
        "Maybe the right move is just a smaller one than you imagined.",
        "Holding the question doesn't make you smaller.",
        "Small hesitations are not proof of failure.",
        "There is space for unsure plans and quiet experiments.",
        "Not deciding is still a shape of decision.",
        "Leave room for answers that arrive sideways.",
        "New things show up when nothing is forced.",
        "Let this be a draft for now.",
        "The quiet in between answers is not empty.",
        "Changing your mind tomorrow is an option.",
        "Paper maps get folded over; some plans will too.",
        "Use the small evidence you have to sketch a simpler story.",
        "A thin hope is still a thread.",
        "If it feels heavy, think about it like a bookmark.",
        "Not knowing can be a quiet kind of listening.",
        "No one needs an explanation for your pause.",
        "Sometimes the right move is to keep walking and notice where the road softens.",
        "Feeling two things at once is normal.",
        "This is a version, not the final edition.",
        "Allow a little mess to test the edges.",
        "Questions are better companions than sudden decisions.",
        "Hold onto curiosity more than certainty tonight.",
        "A choice made from less noise might surprise you.",
        "Loving something for now doesn't require a forever promise."
      ],
      "frustration": [
        "This one can stay rough. It does not need to sound nice yet.",
        "Some days are not made for pretending everything is fine.",
        "Today the clouds look a little scribbly too.",
        "If it is annoying, this note can frown with you for a while.",
        "You do not have to put the hurt away immediately.",
        "When things get stuck, even the air feels louder.",
        "It's annoying when tiny things balloon into ruined plans.",
        "Honestly, the waiting does most of the damage.",
        "Not every mess needs an explanation right away.",
        "Mostly I'm tired of having to translate feelings into neat reasons.",
        "Funny how a split-second can rewrite your whole day.",
        "Left to myself, I replay the same small grievance on loop.",
        "Tiny defeats add up until nothing feels light anymore.",
        "I keep telling myself this will pass, then the clock proves me wrong.",
        "Maybe the problem is bigger than the checklist of fixes we keep trying.",
        "Everything that was calm yesterday is quietly in a bad mood today.",
        "Half the time I resent that nothing dramatic happens to justify feeling like this.",
        "Nobody warned me how boring being frustrated could feel.",
        "The smallest interruption can feel like a personal betrayal.",
        "Long sighs become part of the furniture before you notice.",
        "Little gestures that should help instead land like more things to do.",
        "Can't tell if I'm stuck or just avoiding the thing that needs doing.",
        "Broken plans hang in the hall like unpaid bills.",
        "Quietly, annoyance has its own rhythm and it doesn't always need fixing.",
        "Plain frustration sits stubbornly, like gum on a shoe.",
        "All the polite smiles feel like sandpaper today.",
        "Suddenly I'm tired of explaining why I'm quiet.",
        "Otherwise reasonable people say tiny things that land like shoves.",
        "Still, irritation can wobble on its own and then settle.",
        "For now, I'll let the annoyance sit on the table like an unfinished cup."
      ],
      "gratitude": [
        "This thank-you can stay on the wall.",
        "That is good. A day that is a little easier is still worth noting.",
        "The wall received it.",
        "Your thank-you looks a little warm.",
        "Someone passing by got a small piece of it too.",
        "Someone caught the kindness. That feels good.",
        "The barista remembered my usual and it made the line feel lighter.",
        "My neighbor watered my plant when I forgot; the leaves look relieved.",
        "The bus driver waited and I didn’t have to sprint.",
        "A person lifted my dropped grocery bag and walked on as if nothing happened.",
        "That stranger's smile at the crosswalk softened an otherwise gray morning.",
        "My playlist queued the exact song and the walk home suddenly fit.",
        "A friend texted 'thinking of you' and it landed like a small warmth.",
        "I found a seat on the crowded train and felt oddly lucky.",
        "Someone quietly picked up the tab and didn't turn it into a deal.",
        "Sunlight hit the corner table just right and my coffee tasted better for it.",
        "The neighbor's dog plopped down and demanded belly scratches; I obliged and laughed.",
        "A teammate handled the late email thread so I could close my laptop without worry.",
        "A busker played a song that matched my mood exactly as I walked by.",
        "The library book I returned had a sticky note that said 'hope you enjoyed it.'",
        "The copier finally stopped jamming and I fist-bumped the empty room.",
        "Leftover cake in the break room felt like a tiny celebration.",
        "An elevator stranger complimented my shoes and I carried that for the day.",
        "My surviving houseplant proved it's tougher than I give it credit for.",
        "An umbrella was offered during a downpour and I didn't feel like asking.",
        "An extra napkin appeared right when my coffee betrayed me.",
        "Dinner didn't collapse tonight; my improvised recipe worked out.",
        "A sibling's meme landed at exactly the wrong meeting and I nearly lost it.",
        "Someone held the door while I juggled bags and it was perfectly timed.",
        "A short thank-you note on the fridge for the building cleaner made the whole hallway brighter."
      ],
      "share": [
        "I imagined that cloud.",
        "This one deserves to stay.",
        "Maybe you had been waiting for this day for a while.",
        "It is nice that you noticed such a small thing.",
        "Okay, the wall has one more picture today.",
        "A note that is a little happy for you.",
        "Found a coin on the sidewalk and kept it because why not.",
        "Left this because the light hit it just right.",
        "Saw you smiling at nothing and wanted to mark the moment.",
        "Remember when the bus was late and we laughed about it.",
        "Today felt like a small, unnecessary victory.",
        "Some things are quietly stubborn and that feels good.",
        "Small wonders live in plain sight, held by the everyday.",
        "If the music fit the moment, remember that sound.",
        "There was a tiny bookstore two blocks away yesterday.",
        "Someone left a stamp collection in a drawer once and it smelled like summer.",
        "The coffee here tastes like a memory I can't place.",
        "Another day, another scribble that somehow feels honest.",
        "Nearby, a cat judged a passerby and proceeded to nap.",
        "Before you ask, yes, this is unofficially approved by the wall.",
        "After the rain, the city feels like it borrowed new colors.",
        "No need to overthink the little gifts strangers leave in odd places.",
        "Still, the postcard from somewhere you haven't been is charming.",
        "Quietly, the streetlamp hummed like an old radio.",
        "We once traded jokes for a parking spot and it felt fair.",
        "Bright afternoons make ordinary errands feel cinematic.",
        "Handwritten things age like small time capsules.",
        "Odd little triumphs deserve to be noted, even if it's just a scribble.",
        "Late-night conversations leave strange, honest residue.",
        "Curiosity is why someone stuck a postcard here, and that's enough reason."
      ],
      "blessing": [
        "I hope a little of that wish finds its way back to you.",
        "That wish can take one lap around the wall.",
        "Someone received the good thing you left.",
        "I will put a little more beside it.",
        "I hope you get something warm today too.",
        "Let the coffee in your cup be exactly the temperature you wanted.",
        "Quietly, a free bench waits where you want to sit.",
        "If a stranger smiles, may it stop being small and feel real.",
        "On your walk, a song starts playing that matches your steps.",
        "Tonight the streetlight turns green right as you step out.",
        "When the bus arrives, it happens to be the empty one.",
        "Somewhere nearby, the exact book you want appears on a shelf.",
        "Here's a small wish: your umbrella opens and does its job.",
        "Imagine a sweater that fits like an old favorite, without trying.",
        "The lost coin rolls right under the couch where you always look.",
        "Find a text that says nothing urgent, just hello.",
        "Wishing the oven timer is merciful when you check it by mistake.",
        "Between two meetings, a minute comes that feels like a break.",
        "For no reason, someone remembers your usual order and gets it right.",
        "One small cloud misses your plans and lets the sun stay.",
        "Here's to the awkward pause resolving into a shared laugh.",
        "Perhaps the sun warms the exact bench you pick for lunch.",
        "Hopes that the sandwich you choose turns out even better than you expected.",
        "May the phone battery hold long enough to let you take the photo you want.",
        "At the corner, the vendor has one of your favorites left.",
        "As you step outside, the breeze is exactly the kind that helps.",
        "This tiny favor comes: the parking spot is empty when you arrive.",
        "There is a seat on the train that nobody asks for.",
        "In case you're wondering, the recipe actually works the first time.",
        "So the small thing you postponed is easier than you thought."
      ],
      "affirmation": [
        "This looks like a sentence worth keeping for a while.",
        "Let me borrow my eyes for a second. Yeah, that is a good one.",
        "Some words do not need to be useful yet. You can keep them because you like them.",
        "Do not take this one down.",
        "It looks like a sentence that could stay a long time.",
        "A tiny snail is walking slowly beside this.",
        "Keep it nearby, like a postcard someone once sent.",
        "Hidden between other notes, it waits without asking for attention.",
        "Paper remembers where it sat; this one has good bones.",
        "Quiet things can make a room feel less rushed.",
        "Today this felt worth pinning up. That feeling has weight.",
        "Notice the sentence that doesn't try to fix anything.",
        "There is no immediate reason for it to exist, and that's fine.",
        "These few words are allowed to be ornamental.",
        "I like how it sits on the wall like a small secret.",
        "Strange little comforts live in plain handwriting.",
        "Maybe it stayed because it made you blink.",
        "Nobody needs to explain why it's here.",
        "Small sentences take up only as much space as they need.",
        "When the light hits this note, it seems to mean something different.",
        "On a crowded wall, this has its own quiet rhythm.",
        "Under other thoughts, it still feels steady.",
        "Between errands and emails, this is an honest pause.",
        "Left where the eye tends to wander, it becomes a small landmark.",
        "Right now the wall is more than a collection; it's a map.",
        "Still, it doesn’t demand to be understood.",
        "Remember that some lines are simply companions for the day.",
        "Softly written, but it keeps its shape.",
        "Awhile ago someone liked the way these words sounded; that still matters.",
        "Old scraps and new ideas can coexist without explanation."
      ],
      "complex": [
        "That is a lot to arrive all at once. Anyone would have trouble picking just one thing to talk about.",
        "You do not have to make it neat first. This page is big enough to hold it for now.",
        "When everything crowds in at once, of course your head feels full.",
        "I do not know all of it, but this season sounds heavy.",
        "These words can sit together for now.",
        "When the list multiplies, attention feels like a single thread being pulled thin.",
        "Not everything here is the same kind of problem; label them later if you want.",
        "Some thoughts are stubborn because they belong to someone else's calendar.",
        "A few things will keep returning until they get a little space.",
        "You don't need the whole map right now; a corner will do.",
        "It is honest to feel both annoyed and exhausted at once.",
        "This stack of notes looks chaotic because real life doesn't file itself.",
        "There are soft, small things mixed in with the loud, important ones.",
        "Let the mess be evidence, not judgement.",
        "Some pieces here are questions wearing out their shoes.",
        "Maybe the most helpful thing is noticing how heavy the room feels.",
        "You might find clarity by changing nothing and reading again tomorrow.",
        "The reason you can't pick one thing is because your days are braided together.",
        "These scribbles are a map of attention, not of failure.",
        "A single quiet fact can make everything else rearrange.",
        "It's okay if the order is wrong; order doesn't decide truth.",
        "Keeping some things private is a reasonable option.",
        "Some days will only allow you to notice, not resolve.",
        "These notes are doing the quiet work of turning noise into something you can see.",
        "When every topic clamors, the quiet ones can be the hardest to hear.",
        "You're allowed to be inconsistent; complexity looks like that.",
        "Old resentments and new worries are bunched together through no one's fault.",
        "This pile is a timeline written in half sentences.",
        "A few things here might be smaller than they feel; a few might be bigger.",
        "For now, let these lines be company rather than instructions."
      ],
      "silence": [
        "Looks like the words took the day off.",
        "I will leave a note with no words, then.",
        "Mm. This note nodded.",
        "A single symbol still counts as coming by.",
        "The room is listening to its own furniture.",
        "Someone folded the silence into a paper plane.",
        "There is an argument with the clock.",
        "Chair remembers the shape of a pause.",
        "This wall prefers quiet punctuation.",
        "Checked the silence; it winked back.",
        "Paper held its breath on the corner.",
        "Window fogged with an idea of nothing.",
        "Half the sentence wandered off without notice.",
        "Footsteps stopped to admire the absence.",
        "Light moved across the page like an apology.",
        "Microwave hummed as if it had secrets.",
        "Door kept its mouth closed.",
        "Coffee cooled in solidarity with the quiet.",
        "Second hands rehearsed not-ticking.",
        "Old chairs know better than to interrupt.",
        "Tiny gaps make a strong hush.",
        "Shelf held back a single, small sound.",
        "Phone blinked but didn't say anything.",
        "Air felt like a well-timed pause.",
        "Echo cleared its throat and left.",
        "Post-it scored a silent note in the corner.",
        "Quietly, the hallway agreed to stay out of it.",
        "Nobody announced the meeting of two silences.",
        "Left the page mostly blank, like consent.",
        "Space kept its promises between sentences."
      ],
      "neutral": [
        "A note from someone passing by.",
        "This patch of wall could use a little more color.",
        "There was a small blank spot here.",
        "Nothing big to say. Just leaving a note.",
        "The wall is getting a little busier, slowly.",
        "For the next person who passes by.",
        "Left a tiny square so the wall looks less lonely.",
        "Spotted a faded sticker near the corner.",
        "If you're reading this, hello from another day.",
        "I liked the light here this afternoon.",
        "Added a dash of color because it felt right.",
        "No agenda. Just the sound of people passing.",
        "Saw a dog wag its tail and thought to add this.",
        "An ordinary day gets an ordinary mark.",
        "One more note makes the pattern a little better.",
        "Quiet hello for whoever notices.",
        "Tucked this in between two brighter squares.",
        "Random small thing left by someone who liked the spot.",
        "Feels like a pause in the day.",
        "Not much to add beyond this note.",
        "Keeping the spot company for a few minutes.",
        "Small paper, small gesture, small moment.",
        "Here's a square to break up the gray.",
        "Marked this place simply because I passed by.",
        "Curious how many of these will stack up.",
        "Unremarkable, except for being shared.",
        "That spot looked like it could use a tiny interruption.",
        "Leaving a small trace of someone else's afternoon.",
        "Colors here remind me of old notebooks.",
        "Tiny square to keep things interesting."
      ]
    }
  },
  "RESPONSE_TAILS": {
    "zh": {
      "fatigue": [
        "",
        "\n\n今天先到這裡也可以。",
        "\n\n（重要的事情要再說一次）希望你回去的路上有一小段很安靜。",
        "\n\n遲一點再想，不會扣分。",
        "\n\n我幫你在旁邊畫了個快睡著的太陽。"
      ],
      "lonely": [
        "",
        "\n\n我不太會講話，但不想讓這張紙只有自己。",
        "\n\n這裡有人看到了。",
        "\n\n路過的時候停了一下。",
        "\n\n我在旁邊貼一張，免得它太空。"
      ],
      "uncertain": [
        "",
        "\n\n今晚不用把答案找完。",
        "\n\n明天再看也還是你的事。",
        "\n\n先選一個比較不難的步驟就好。",
        "\n\n我也有好多次不知道下一步。"
      ],
      "frustration": [
        "",
        "\n\n這種煩真的不是深呼吸三次就會散掉的。",
        "\n\n如果想罵一句，也可以。",
        "\n\n先不要急著原諒任何人。",
        "\n\n今天的心情也有點亂。"
      ],
      "gratitude": [
        "",
        "\n\n這句謝謝看起來很暖。",
        "\n\n我也被分到一點點。",
        "\n\n兜兜轉轉，好事終於如期而至。",
        "\n\n希望那個人也剛好看見。"
      ],
      "share": [
        "",
        "\n\n我會記得今天牆上有這件事。",
        "\n\n你看到它的時候，應該有一點開心吧。",
        "\n\n這種好事要先讓它待久一點。",
        "\n\n我在角落畫個小圓圈，圈住它。"
      ],
      "blessing": [
        "",
        "\n\n也祝你剛好被好好對待。",
        "\n\n我把這個願望放大一點點。",
        "\n\n希望它會繞一圈回到你這裡。",
        "\n\n有人路過，收到你的好意。"
      ],
      "affirmation": [
        "",
        "\n\n這句不要撕掉。",
        "\n\n我想把它抄在自己的本子上。",
        "\n\n它看起來很適合陪很久。",
        "\n\n旁邊留個歪掉的愛心。"
      ],
      "complex": [
        "",
        "\n\n像桌上同時堆了太多東西，怎樣都清不完。",
        "\n\n你不用現在替它們分類。",
        "\n\n讀到這裡，提醒你停一下。",
        "\n\n先讓這些字在牆上透透氣。"
      ],
      "silence": [
        "",
        "\n\n我也不講話，畫個月亮陪你。",
        "\n\n今天只放這個，也算數。",
        "\n\n這張紙點了點頭。",
        "\n\n我在旁邊放一顆快睡著的星星。"
      ],
      "neutral": [
        "",
        "\n\n剛好經過。",
        "\n\n今天這裡多了一點顏色。",
        "\n\n留給下一個路過的人。",
        "\n\n我沒有什麼好說的，還是貼一張。"
      ]
    },
    "en": {
      "fatigue": [
        "",
        "\n\nStopping here today still counts.",
        "\n\nI hope one part of your way home is quiet.",
        "\n\nThinking about it later does not lose you points.",
        "\n\nI drew a sun that looks ready for a nap."
      ],
      "lonely": [
        "",
        "\n\nI am not great with words. I just did not want this note alone.",
        "\n\nSomeone saw this.",
        "\n\nI stopped for a second while passing by.",
        "\n\nLeaving one beside it so the space feels less empty."
      ],
      "uncertain": [
        "",
        "\n\nYou do not have to finish finding the answer tonight.",
        "\n\nIt will still be your question tomorrow.",
        "\n\nMaybe pick the least difficult next step.",
        "\n\nI have had plenty of days with no next step either."
      ],
      "frustration": [
        "",
        "\n\nThis kind of annoying does not disappear after three deep breaths.",
        "\n\nYou can complain a little if you need to.",
        "\n\nNo need to forgive anyone in a hurry.",
        "\n\nThe clouds are scribbly today too."
      ],
      "gratitude": [
        "",
        "\n\nYour thank-you looks warm.",
        "\n\nI got a small piece of it too.",
        "\n\nGood things really do land sometimes.",
        "\n\nI hope that person sees it somehow."
      ],
      "share": [
        "",
        "\n\nI will remember this was on the wall today.",
        "\n\nYou must have smiled a little when you saw it.",
        "\n\nLet the good thing stay around for a while.",
        "\n\nI drew a little circle around it."
      ],
      "blessing": [
        "",
        "\n\nI hope you get treated gently too.",
        "\n\nMaking that wish a tiny bit bigger.",
        "\n\nMaybe it will make one lap and come back to you.",
        "\n\nSomeone passing by received your kindness."
      ],
      "affirmation": [
        "",
        "\n\nDo not take this one down.",
        "\n\nI want to copy it into my own notebook.",
        "\n\nIt looks like it could stay for a long time.",
        "\n\nLeaving a crooked heart beside it."
      ],
      "complex": [
        "",
        "\n\nLike too many things piling up on one desk at once.",
        "\n\nYou do not have to sort them by size right now.",
        "\n\nI paused here for a bit.",
        "\n\nLet these words get some air on the wall."
      ],
      "silence": [
        "",
        "\n\nI will not say anything either. Just drawing a moon.",
        "\n\nThis still counts today.",
        "\n\nThis note nodded.",
        "\n\nLeaving a sleepy star beside it."
      ],
      "neutral": [
        "",
        "\n\nJust happened to pass by.",
        "\n\nA little more color showed up here today.",
        "\n\nFor the next person who stops here.",
        "\n\nNothing clever to say, so I left a note."
      ]
    }
  },
  "BLOCKED_PHRASES": {
    "zh": [
      "你要加油",
      "想開一點",
      "你可以做到",
      "你一定可以",
      "這個考驗",
      "因為你有能力",
      "去喝一口溫的東西",
      "吃點東西，洗個澡",
      "早一點躺下",
      "不是你懶",
      "你沒有落後"
    ],
    "en": [
      "you can do it",
      "cheer up",
      "everything happens for a reason",
      "this test came because",
      "go eat",
      "take a shower",
      "go to sleep",
      "you are not behind"
    ]
  }
};
